import Banner from "@/components/Banner";
import Head from "next/head";
import * as S from "@/styles";
import Document from "@/components/Document";

export default function Home() {
  return (
    <>
      <S.GlobalStyle />
      <Head>
        <title>Regras - Zero City</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>
      <Banner />
      <Document />
    </>
  );
}
